app/controllers/capsules_controller.rb
app/models/capsule.rb
db/migrate/20230320134823_create_capsules.rb
db/schema.rb
test/controllers/capsules_controller_test.rb
test/models/capsule_test.rb

Routes faites, controller bientôt terminé

routes faites, controller en cours

---

app/controllers/capsules_controller.rb
app/models/capsule.rb
app/views/capsules/index.html.erb
app/views/capsules/show.html.erb
config/routes.rb

controller routes and views OK pour Capsules

controller routes and views OK

---

app/controllers/bookings_controller.rb
app/controllers/capsules_controller.rb
app/models/booking.rb
config/routes.rb
db/migrate/20230320154643_create_bookings.rb
test/controllers/bookings_controller_test.rb
test/models/booking_test.rb

controller routes OK pour Bookings

controller routes OK pour Bookings

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_capsule-card.scss
app/assets/stylesheets/components/_index.scss
app/views/capsules/index.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

1ère partie de la show page des capsules -> partie avec les cards des capsules

Capsules index

---

app/controllers/capsules_controller.rb
db/migrate/20230320162411_add_description_to_capsules.rb
db/schema.rb

db:migrate AddDescriptionToCapsules

AddDescriptionToCapsules

---

app/assets/stylesheets/pages/_index.scss

import des fichiers css dans _index.scss

import css pour show page capsule

---

app/assets/stylesheets/pages/_index.scss

; à rajouter dans ligne import (dans index.scss)

update page show import css

---

app/assets/stylesheets/pages/_index.scss

encore update import css page show

---

Gemfile
Gemfile.lock
app/controllers/users_controller.rb
db/schema.rb
db/seeds.rb

Seeds mise à jours ( j'ai tout réparé tout seul)

Model userv2

---

db/seeds.rb

seeds capsules update

---

app/controllers/users_controller.rb

private params users

---

app/models/booking.rb
db/migrate/20230321172914_remove_not_null_constraint_from_bookings_review_id.rb
db/migrate/20230321203031_add_booking_to_reviews.rb
db/migrate/20230321221134_remove_review_from_bookings.rb
db/schema.rb
db/seeds.rb

correction des liens entre review et booking
& ajouts de seeds pour tous les modèles
**après le pull il faut faire un rails db:drop db:create db:migrate db:seed**

correction des liens entre review et booking

---

app/controllers/bookings_controller.rb
app/controllers/users_controller.rb
app/views/users/show.html.erb
config/routes.rb

la réservation fonctionne et s'affiche bien sur /users/user_id/ (mais front pas fait)

form booking ok mais show non formatee

---

app/views/capsules/index.html.erb

ajout d'un lien cloudinary dans index

fix search function

---

app/controllers/bookings_controller.rb
app/views/users/show.html.erb

annuler une résa feature fonctionne (depuis son user espace)

delete booking ok

---

app/controllers/capsules_controller.rb
app/models/capsule.rb
app/views/capsules/new.html.erb
app/views/capsules/show.html.erb
app/views/pages/home.html.erb
db/seeds.rb

seeds update

---

app/javascript/controllers/price_count_controller.js
app/views/capsules/_form_new_booking.html.erb
app/views/capsules/show.html.erb

calcul du prix total avant de réserver + front (basique et sans CSS)

total price count

---

app/controllers/bookings_controller.rb
app/javascript/controllers/price_count_controller.js
app/views/capsules/_form_new_booking.html.erb

Ajout automatique du tarif total de réservation en base de données

total price

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_product_card.scss
app/views/users/show.html.erb

pending_booking html

---

app/assets/stylesheets/components/_product_card.scss
app/views/users/show.html.erb

card pour voir les résas en attente et format de date en dd-mm-yyyy (au lieu de yyyy-mm-dd)

booking en attente et date en bon format

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_user-profil.scss
app/views/users/show.html.erb

boutons pour naviguer plus rapidement sur la page

naviguer dans page user

---

app/assets/stylesheets/pages/_capsule.scss
app/views/shared/_navbar.html.erb

Mises à jour de la Show User (alignement et sticky positionnement)
Enlever le bouton résa du dropdown menu

updates show user & drop down menu
